name: dart_constructs
author: Kyle Ferguson <hanbrolo117@gmail.com>
description: As of now, the constructs project has one data structure, that is the nth dimensional matrix construct. Say I want to make a 4 dimensional integer matrix, I would simply type NMatrix<int> nm4 = new NMatrix.dimensional([1,2,3,4],5); That's it!;
