name: dart_constructs
version: 1.1.2
description: As of now, the constructs project has one data structure, that is the nth dimensional matrix construct. Say I want to make a 3x3x3x3 integer matrix initialized with a value of 5, I would simply type NMatrix<int> nm4 = new NMatrix.dimensional([3,3,3,3],5); That's it!
author: Kyle Ferguson <hanbrolo117@gmail.com>
homepage: https://hanbrolo117.github.io/Dart-Constructs/
publish_to: http://pub.dartlang.org
